<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class InstitutionSeeder extends Seeder
{
    public function run(): void
    {
        $institutions = [
            [
                'name' => 'Stanford University',
                'description' => 'Один из ведущих частных исследовательских университетов мира, расположенный в Кремниевой долине.',
                'country' => 'США',
                'city' => 'Stanford',
                'type' => 'university',
                'image_url' => 'https://www.estudy.ru/upload/ammina.optimizer/jpeg-webp/q80/upload/iblock/6b8/ra5e59nqibp6esl014axdwe154d0ytmu.webp',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Информационные технологии', 'Бизнес', 'Инженерия', 'Медицина']),
                'price_from' => 55000,
                'price_to' => 75000,
                'currency' => 'USD',
                'views' => 0,
            ],
            [
                'name' => 'MIT',
                'description' => 'Массачусетский технологический институт - мировой лидер в области науки и технологий.',
                'country' => 'США',
                'city' => 'Cambridge',
                'type' => 'university',
                'image_url' => 'https://tse1.mm.bing.net/th/id/OIP.qY0g0xauaMpU1qlrVwMMswHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Информационные технологии', 'Инженерия', 'Бизнес']),
                'price_from' => 53000,
                'price_to' => 72000,
                'currency' => 'USD',
                'views' => 0,
            ],
            [
                'name' => 'Harvard University',
                'description' => 'Старейший университет США, входящий в Лигу плюща.',
                'country' => 'США',
                'city' => 'Cambridge',
                'type' => 'university',
                'image_url' => 'https://duhocthanhcong.vn/wp-content/uploads/school-photos/Harvard%20University/Harvard-University-Album1.jpeg',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Бизнес', 'Медицина', 'Информационные технологии']),
                'price_from' => 58000,
                'price_to' => 78000,
                'currency' => 'USD',
                'views' => 0,
            ],
            [
                'name' => 'University of Tokyo',
                'description' => 'Ведущий исследовательский университет Японии, известный своими научными достижениями.',
                'country' => 'Япония',
                'city' => 'Tokyo',
                'type' => 'university',
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUhocfot3y9Sw5aQzc4-SfhkMuy68bbZyV4Q&s',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Инженерия', 'Информационные технологии']),
                'price_from' => 4500,
                'price_to' => 8500,
                'currency' => 'USD',
                'views' => 0,
            ],
            [
                'name' => 'Kyoto University',
                'description' => 'Второй по старшинству университет Японии, известный исследованиями в области физики и химии.',
                'country' => 'Япония',
                'city' => 'Kyoto',
                'type' => 'university',
                'image_url' => 'https://smapse.ru/storage/2019/10/a3-3.jpg',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Медицина', 'Инженерия']),
                'price_from' => 4200,
                'price_to' => 8000,
                'currency' => 'USD',
                'views' => 0,
            ],
            [
                'name' => 'Tokyo Galaxy Japanese Language School',
                'description' => 'Tokyo Galaxy Japanese Language School предлагает различные курсы обучения, факультативные занятия, эффективные методики и качественные учебные материалы. Обучение строится в зависимости от целей студента и его уровня образования и владения японским языком. Tokyo Galaxy Japanese Language School - одна из лучших вариантов в Токио для комфортного и эффективного изучения японского языка, а также, дальнейшего образования и трудоустройства.',
                'country' => 'Япония',
                'city' => 'Tokyo',
                'type' => 'Language School',
                'image_url' => 'https://study-japan-guide.com/media/images/TOKYO%20GALAXY-2.jpg',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Языковые курсы']),
                'price_from' => 4200,
                'price_to' => 8000,
                'currency' => 'USD',
                'views' => 0,
            ],
            [
                'name' => 'University of Oxford',
                'description' => 'Старейший англоязычный университет в мире, основанный в 1096 году.',
                'country' => 'Великобритания',
                'city' => 'Oxford',
                'type' => 'university',
                'image_url' => 'https://accommodationforstudents.com/cdn-cgi/image/f=auto,q=85,w=960/https://images.accommodationforstudents.com/website/university-guides/gb/university-of-oxford/uni.jpg',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Бизнес', 'Медицина', 'Информационные технологии']),
                'price_from' => 25000,
                'price_to' => 45000,
                'currency' => 'GBP',
                'views' => 0,
            ],
            [
                'name' => 'Imperial College London',
                'description' => 'Ведущий мировой университет в области науки, инженерии, медицины и бизнеса.',
                'country' => 'Великобритания',
                'city' => 'London',
                'type' => 'university',
                'image_url' => 'https://yourdreamschool.com/wp-content/uploads/2020/10/shutterstock_770971315-e1529418948592.jpg',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Инженерия', 'Медицина', 'Информационные технологии']),
                'price_from' => 32000,
                'price_to' => 48000,
                'currency' => 'GBP',
                'views' => 0,
            ],
            [
                'name' => 'University of Toronto',
                'description' => 'Ведущий государственный исследовательский университет Канады.',
                'country' => 'Канада',
                'city' => 'Toronto',
                'type' => 'university',
                'image_url' => 'https://d3d0lqu00lnqvz.cloudfront.net/media/media/UofT_cmh2315fl.jpg',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Информационные технологии', 'Бизнес', 'Медицина']),
                'price_from' => 28000,
                'price_to' => 52000,
                'currency' => 'CAD',
                'views' => 0,
            ],
            [
                'name' => 'University of British Columbia',
                'description' => 'Исследовательский университет мирового класса, расположенный в Ванкувере.',
                'country' => 'Канада',
                'city' => 'Vancouver',
                'type' => 'university',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Irving_K._Barber_Library.jpg/1200px-Irving_K._Barber_Library.jpg',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Инженерия', 'Бизнес']),
                'price_from' => 26000,
                'price_to' => 50000,
                'currency' => 'CAD',
                'views' => 0,
            ],

            // Австралия
            [
                'name' => 'University of Sydney',
                'description' => 'Первый университет Австралии, основанный в 1850 году.',
                'country' => 'Австралия',
                'city' => 'Sydney',
                'type' => 'university',
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgcMLCqa4xCPshS7xgcb3rGqdxqi3S-_PYrw&s',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Бизнес', 'Медицина', 'Информационные технологии']),
                'price_from' => 35000,
                'price_to' => 55000,
                'currency' => 'AUD',
                'views' => 0,
            ],
            [
                'name' => 'University of Melbourne',
                'description' => 'Ведущий исследовательский университет Австралии, известный высоким качеством образования.',
                'country' => 'Австралия',
                'city' => 'Melbourne',
                'type' => 'university',
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbDCjvmPFZh3T7BC6V_UTkVHCj0ALGUcooKQ&s',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Инженерия', 'Медицина', 'Бизнес']),
                'price_from' => 38000,
                'price_to' => 58000,
                'currency' => 'AUD',
                'views' => 0,
            ],
            [
                'name' => 'Tokyo Institute of Technology',
                'description' => 'Ведущий национальный университет Японии, специализирующийся на науке и технологиях.',
                'country' => 'Япония',
                'city' => 'Tokyo',
                'type' => 'college',
                'image_url' => 'https://www.titech.ac.jp/english/gallery/mainimg-about-news-35063.jpg',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Информационные технологии', 'Инженерия']),
                'price_from' => 4000,
                'price_to' => 7500,
                'currency' => 'USD',
                'views' => 0,
            ],
            [
                'name' => 'California Institute of Technology',
                'description' => 'Небольшой частный исследовательский университет в Пасадене, Калифорния.',
                'country' => 'США',
                'city' => 'Pasadena',
                'type' => 'university',
                'image_url' => 'https://allterra.ru/upload/cssinliner_webp/resize_cache/iblock/f31/bzkvkijngrmn9o9csehbzhtdrfxca1cl/925_545_1/California_Institute_of_Technology_12.webp',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Инженерия', 'Информационные технологии']),
                'price_from' => 56000,
                'price_to' => 76000,
                'currency' => 'USD',
                'views' => 0,
            ],
            [
                'name' => 'University of Cambridge',
                'description' => 'Исследовательский университет в Кембридже, Англия, основанный в 1209 году.',
                'country' => 'Великобритания',
                'city' => 'Cambridge',
                'type' => 'university',
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkf9KBsMMe8IzAYYdWmdrFUFv31Ow14PHPuQ&s',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Медицина', 'Инженерия', 'Бизнес']),
                'price_from' => 27000,
                'price_to' => 46000,
                'currency' => 'GBP',
                'views' => 0,
            ],
            [
                'name' => 'McGill University',
                'description' => 'Государственный исследовательский университет в Монреале, Квебек, Канада.',
                'country' => 'Канада',
                'city' => 'Montreal',
                'type' => 'university',
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5Kzat-VxYyfqPFy38t1XkDwa9DtjC3rthog&s',
                'rating' => 0,
                'featured' => false,
                'programs' => json_encode(['Медицина', 'Информационные технологии']),
                'price_from' => 29000,
                'price_to' => 53000,
                'currency' => 'CAD',
                'views' => 0,
            ],
        ];

        $now = now();
        foreach ($institutions as &$institution) {
            $institution['created_at'] = $now;
            $institution['updated_at'] = $now;
        }

        DB::table('institutions')->insert($institutions);
    }
}
