version: '3.8'

services:
  # Только интернет-банк (фронтенд)
  ibank:
    image: nginx:latest
    container_name: ${STACK_NAME}_ibank
    ports:
      - "80"
    restart: unless-stopped
    labels:
      - "sandbox=${STACK_NAME}"
      - "type=ibank"
