version: '3.8'

services:
  # Только интернет-банк (фронтенд)
  ibank:
    image: nginx:alpine
    container_name: ${STACK_NAME}_ibank
    ports:
      - "${IB_PORT:-8080}:80"
    volumes:
      - ./ibank:/usr/share/nginx/html
      - ./nginx/ibank.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ibank-network
    restart: unless-stopped
    labels:
      - "sandbox=${STACK_NAME}"
      - "type=ibank"

networks:
  ibank-network:
    driver: bridge